-- Step 3: Create main entity tables

-- Table for Customers
CREATE TABLE customers (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    name text NOT NULL,
    email text UNIQUE,
    phone text,
    address text,
    city text,
    state text,
    zip_code text,
    status_id uuid REFERENCES customer_statuses(id) ON DELETE SET NULL,
    join_date timestamptz DEFAULT now(),
    last_order_date timestamptz,
    total_orders integer DEFAULT 0,
    total_spent numeric DEFAULT 0,
    average_order_value numeric DEFAULT 0,
    notes text,
    tags text[],
    avatar text,
    preferences jsonb,
    loyalty_points integer DEFAULT 0,
    loyalty_tier_id uuid REFERENCES loyalty_tiers(id) ON DELETE SET NULL,
    birthday date,
    referral_source text,
    marketing_consent boolean DEFAULT false,
    sms_consent boolean DEFAULT false,
    analysis jsonb,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Table for Products
CREATE TABLE products (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    category_id uuid REFERENCES product_categories(id) ON DELETE SET NULL,
    name text NOT NULL,
    description text,
    image_url text,
    price numeric NOT NULL,
    cost numeric,
    is_available boolean DEFAULT true,
    is_featured boolean DEFAULT false,
    track_inventory boolean DEFAULT false,
    stock_quantity integer,
    low_stock_threshold integer,
    calories integer,
    allergens text[],
    dietary_tags text[],
    tags text[],
    ingredients text[],
    nutritional_info jsonb,
    customization_options jsonb,
    ai_recommendation_score numeric,
    total_orders integer DEFAULT 0,
    total_revenue numeric DEFAULT 0,
    sort_order integer DEFAULT 0,
    monthly_data jsonb,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Table for Orders
CREATE TABLE orders (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    customer_id uuid REFERENCES customers(id) ON DELETE SET NULL,
    order_number text NOT NULL,
    status_id uuid REFERENCES order_statuses(id),
    order_type text,
    customer_name text,
    customer_email text,
    customer_phone text,
    delivery_address text,
    delivery_instructions text,
    subtotal numeric NOT NULL,
    tax_amount numeric DEFAULT 0,
    tip_amount numeric DEFAULT 0,
    discount_amount numeric DEFAULT 0,
    total_amount numeric NOT NULL,
    payment_method text,
    payment_status_id uuid REFERENCES payment_statuses(id),
    payment_intent_id text,
    assigned_to uuid REFERENCES staff(id) ON DELETE SET NULL,
    special_instructions text,
    notes text,
    tags text[],
    estimated_prep_time integer,
    estimated_delivery_time timestamptz,
    completed_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Table for Order Items
CREATE TABLE order_items (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id uuid REFERENCES products(id) ON DELETE SET NULL,
    name text NOT NULL,
    description text,
    quantity integer NOT NULL,
    unit_price numeric NOT NULL,
    total_price numeric NOT NULL,
    notes text,
    customizations jsonb,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);
